// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZzLz9u0uYIccXLi57ffy6Yt2brlovRV8',
    appId: '1:614290512463:web:4dd4f5d1dd6e394ec5683a',
    messagingSenderId: '614290512463',
    projectId: 'sams-3a077',
    authDomain: 'sams-3a077.firebaseapp.com',
    storageBucket: 'sams-3a077.firebasestorage.app',
    measurementId: 'G-0RZQR75V8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGM0bwR6k5gHA6iiF84EX45AKNd7G6PV0',
    appId: '1:614290512463:android:fcd22c71176aa3cbc5683a',
    messagingSenderId: '614290512463',
    projectId: 'sams-3a077',
    storageBucket: 'sams-3a077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMsUrRKz9OjEoJc5M6USg_2qCkF8uGPI8',
    appId: '1:614290512463:ios:23613df278f57712c5683a',
    messagingSenderId: '614290512463',
    projectId: 'sams-3a077',
    storageBucket: 'sams-3a077.firebasestorage.app',
    iosBundleId: 'com.example.sams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMsUrRKz9OjEoJc5M6USg_2qCkF8uGPI8',
    appId: '1:614290512463:ios:23613df278f57712c5683a',
    messagingSenderId: '614290512463',
    projectId: 'sams-3a077',
    storageBucket: 'sams-3a077.firebasestorage.app',
    iosBundleId: 'com.example.sams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZzLz9u0uYIccXLi57ffy6Yt2brlovRV8',
    appId: '1:614290512463:web:4a59c7cc231e6f17c5683a',
    messagingSenderId: '614290512463',
    projectId: 'sams-3a077',
    authDomain: 'sams-3a077.firebaseapp.com',
    storageBucket: 'sams-3a077.firebasestorage.app',
    measurementId: 'G-Q3EFQDMK6M',
  );
}
